# The ratemaking process

```{r}
#| label: load-prereqs
#| echo: false
#| message: false

# knitr options
source("_common.R")

```

## Ratemaking principles, considerations and adjustments 

<embed src="files/ca-2-1a-pdf.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-1b-notes.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-1c-notes.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-1d-pdf.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-1-summary.pdf"type="application/pdf" width="100%" height="1000px"></embed>

## Rate and benefit changes

<embed src="files/ca-2-2a-pdf.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-2b-notes.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-2c-notes.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-2d-notes.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-2-summary.pdf"type="application/pdf" width="100%" height="1000px"></embed>

## Development

<embed src="files/ca-2-3a-notes.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-3b-notes.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-3-summary.pdf"type="application/pdf" width="100%" height="1000px"></embed>

## Trending

<embed src="files/ca-2-4a-pdf.pdf"type="application/pdf" width="100%" height="1000px"></embed>

We trend data **from** the historical period **over** the trend period **to** the forecast period.

<embed src="files/ca-2-4b-pdf.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-4c-pdf.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-4d-notes.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-4e-notes.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-4f-notes.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-4-summary.pdf"type="application/pdf" width="100%" height="1000px"></embed>

## Example (not in book) {.unnumbered}

Imagine the following historical data without any adjustments:

Year     | Earned Premium | Incurred Loss
---------|----------------|--------------
2016     | 100            | 90
2017     | 120            | 80
2018     | 125            | 75
**Total**| **345**      | **245**

Now the question we have is, "Is the current price we're charging adequate for our 2019 policies?"

Let's assume our current permissible loss ratio (the LR we need to achieve our desired profit) is 70%. So we measure our total incurred loss divided by our earned premium and get a loss ratio of $245 / 345 = 71\%$, clearly our rates are close, but it looks like we need to bump it up a bit to hit our 70% loss ratio target.

But hang on, we need to take loss adjustments into account. First there's loss development. A losses ultimate settlement value isn't known right away, and depending on the LOB it can develop upwards extremely highly for a long time. Let's assume this is a short tail line and 2016 is fully developed. But we need to multiply 2017 by 1.1 and 2018 to 1.2 to get to our best guess of the ultimate values. Now our ultimate losses is $90 + 80 (1.1) + 75(1.2) = 90 + 88 + 90 = 268$.

But now there's loss trend to account for. This is where inflation and the increased cost of repairs is taken into account (not in premium trend or leveling). If loss trend is 5% a year, our estimate of trended ultimate loss is: $(90 \times 1.05^3) + (88 \times 1.05^2) + (90 \times 1.05^1) = 295.71$. Notice the exponents are chosen to bring each year to the 2019 accident level.

So now our Loss Ratio estimate is $295.71 / 345 = 85.7\%$ and our current rate looks woefully inadequate, but is it? We've adjusted losses properly, but we haven't touched premium.

2016 looks like it was a bad year, what happens if we looked at that in 2017 and decided to raise our rates for the 2018 year? In this example, let's say we raised our rates 20% in 2018. If we don't account for that rate increase, 2016 will still look like it's a bad year and will cause us to raise our rates again, eventually leading to us charging too much. So we need to on-level our premiums to account for this. (If we never changed our rates, on-leveling would not be necessary regardless of exposure base and any other considerations). So our on level premium is:

$100(1.2) + 120(1.2) + 125(1.0) = 120 + 144 + 125 = 389$, this is our on-level premium. It's not taking into account inflation or any extrinsic factors, it's merely reflecting the changes in our own rates that we already implemented from our historical data.

Finally there's premium trend. If this is a commercial property book, insuring the same collection of buildings every year, the exposure, and therefore the premium we collect, is going to rise every year, even if the rate remains the same. Our rate is based not per building, but based on a buildings value. The 100k building that we insured in 2016 might be worth 110k in 2019. So the 500 dollars of premium we have on our books would be 550 dollars in 2019, before accounting for any of our own rate changes. So we'll be collecting more premium in 2019 than we have in our 2016 data.

If it's a law office where we charge per lawyer, there's no need to trend the exposures, and we'd skip this step. 1 lawyer in 2016 is the same as 1 lawyer in 2019 from our rating perspective. Not from an insurance cost perspective (that's what loss trend is for). But the same building in 2016 might generate 10% more premium in 2019, even if we don't change our rates at all. This is why on-leveling isn't sufficient for an inflationary exposure base.

If premium trend is 4% our on-level trended premium is $(120 \times 1.04^3) + (144 \times 1.04^2) + (125 \times 1.04^1) = 420.73$ (again exponents bring each year to 2019).

So let's look at our table again:

Year     | OL Trended EP | Trended Ultimate Incurred Loss
---------|---------------|-------------------------------
2016     | 134.98        | 104.19
2017     | 155.75        | 97.02
2018     | 130           | 94.5
**Total**| **420.73**    | **295.71**

Where each premium number represents how much premium we'd collect for the same risks we had in a prior year if we wrote it it this year, and the loss column represents what we think the ultimate cost would be of those risks this year. So now we can finally look at our total loss ratio and determine that it's nearly bang on 70% ($295.71 / 420.73 = 70.3\%$) and we don't needy to adjust our rates further.

This demonstrates how the difference between on-leveling and premium trend and why both might be necessary.

## Expenses and profit

<embed src="files/ca-2-5a-notes.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-5b-notes.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-5c-notes.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-5d-notes.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-5-summary.pdf"type="application/pdf" width="100%" height="1000px"></embed>

## Overall rate level indications

<embed src="files/ca-2-6a-notes.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-6b-notes.pdf"type="application/pdf" width="100%" height="1000px"></embed>

<embed src="files/ca-2-6-summary.pdf"type="application/pdf" width="100%" height="1000px"></embed>
